### ISSUE TITLE
Add timeline of previous winners

### ISSUE THREAD

**Issue by NuttyShrimp** [12urenloop/site#16]
A nice-to-have request from the org. A almost complete version can be found here: https://github.com/12urenloop/cvc/issues/119, I'll check if they don't have the winners after 2015 stored somewhere

**Comment by Iepoev** [comment]
![A2578927-09D4-429F-92C4-A046EDDA2875](https://user-images.githubusercontent.com/5631570/228062838-835ade08-3570-418a-9cdc-dd11f96b07a3.jpg)

**Comment by smessie** [comment]
Thanks @Iepoev ! If anyone would have the winners after these dates, that would also be highly appreciated :)
